quarkus:
  langchain4j:
    log-requests: true
    log-responses: true
    timeout: 1m
    easy-rag:
      path: src/main/resources/documents
      max-results: 10
    ollama:
      chat-model:
        model-id: mistral
  otel:
    exporter:
      otlp:
        traces:
          protocol: http/protobuf
  tls:
    trust-all: true

"%dev,test":
  quarkus:
    micrometer:
      export:
        otlp:
          url: http://${quarkus.otel-collector.url}/v1/metrics
    otel:
      exporter:
        otlp:
          traces:
            endpoint: http://${quarkus.otel-collector.url}

"%test":
  quarkus:
    langchain4j:
      easy-rag:
        ingestion-strategy: "off"