quarkus:
  langchain4j:
    log-requests: true
    log-responses: true
    timeout: 1m
    easy-rag:
      path: src/main/resources/documents
      max-results: 7
    ollama:
      chat-model:
        model-id: mistral
  otel:
    exporter:
      otlp:
        traces:
          protocol: http/protobuf
  tls:
    trust-all: true

"%test":
  quarkus:
    langchain4j:
      easy-rag:
        ingestion-strategy: "off"