name: Basic build and test

env:
  MANDREL_VERSION: "23.1.2.0-Final"

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build-test-jvm
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0

  jvm-container-build-test:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build-test-jvm-container
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -Dquarkus.container-image.build=true

  native-build-test:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
    steps:
      - uses: actions/checkout@v4

      - name: Cache and restore Mandrel distro
        id: check-mandrel-cache
        uses: actions/cache@v4
        with:
          path: mandrel-${{ env.MANDREL_VERSION }}-21.tar.gz
          key: mandrel-distro-${{ env.MANDREL_VERSION }}-21

      - name: Download Mandrel
        if: steps.check-mandrel-cache.outputs.cache-hit != 'true'
        run: |
          download_url="https://github.com/graalvm/mandrel/releases/download/mandrel-${MANDREL_VERSION}/mandrel-java21-linux-amd64-${MANDREL_VERSION}.tar.gz"
          wget -q -O mandrel-${{ env.MANDREL_VERSION }}-21.tar.gz $download_url

      - name: Setup Maven+OpenJDK Distro
        uses: actions/setup-java@v4
        with:
          distribution: jdkfile
          jdkFile: mandrel-${{ env.MANDREL_VERSION }}-21.tar.gz
          java-version: 21
          architecture: x64
          cache: maven

      - name: build-test-native
        run: ./mvnw -B clean verify -Pnative -Dquarkus.http.host=0.0.0.0 -Dmaven.compiler.release=21

  native-container-build-test:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build-test-native-container
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dquarkus.native.container-build=true \
            -Dquarkus.container-image.build=true \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=21